Handle file rename in git
I found out that if I rename a directory (or a file), it will
generate a line like this:

    R100    roles/example/handlers/main.yml roles/example_old/handlers/main.yml

This break with:

  File "/usr/local/bin/generate_ansible_command.py", line 181, in <module>
    changed_files = get_changed_files(args.git, args.old, args.new)
  File "/usr/local/lib/bastion_lib.py", line 52, in get_changed_files
    (t, f) = l.split()
  ValueError: too many values to unpack

So we need to verify the lenght of the array and assign values accordingly.